name: release
on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/llm-codegen-research

    permissions:
      id-token: write

    steps:

      - name: 1. Checkout the code...
        uses: actions/checkout@v4

      - name: 2. Configure uv...
        uses: astral-sh/setup-uv@v6

      - name: 3. Build the package...
        run: uv build

      - name: 4. Publish package to PyPI
        run: uv publish --trusted-publishing always
