name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # testing job configuration and steps
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # test on the supported python version and the newest
        python-version: ["3.11", "3.12", "3.13"]

    steps:

      - name: 1. Checkout the code...
        uses: actions/checkout@v3

      - name: 2. Configure Python version ${{ matrix.python-version }}...
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: 3. Run the tests...
        run: uv run pytest
