name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # testing job configuration and steps
  test:

    runs-on: ubuntu-latest

    environment:
      name: test

    strategy:
      matrix:
        # test on the supported python version and the newest
        python-version: ["3.11", "3.12", "3.13"]

    steps:

      - name: 1. Checkout the code...
        uses: actions/checkout@v3

      - name: 2. Configure Python version ${{ matrix.python-version }}...
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: 3. Run the tests...
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: uv run pytest
